Repository ArtLibro/artLibro-frontend, pull requests merged in 2025-02, with the labels that each got.

#9 feat: 도서 페이지 퍼블리싱
  public/icons/book-publisher.svg
  public/images/dummy-book.png
  src/apis/books.ts
  src/apis/endpoint.ts
  src/assets/_color.scss
  src/assets/_font.scss
  src/config/axiosLibraryConfig.ts
  src/constans/book-badge.ts
  src/router/index.ts
  src/types/libraryType.ts
  src/views/BookView.vue
  tsconfig.app.json
Labels: featrue

#14 feat: 로그인, 회원가입 페이지 퍼블리싱
  public/icons/SignUp/google.svg
  public/icons/SignUp/kakao.svg
  public/icons/SignUp/logo.svg
  public/icons/SignUp/naver.svg
  public/icons/book-publisher.svg
  public/icons/divider.svg
  public/images/book-dummy.jpg
  public/images/dummy-book.png
  src/App.vue
  src/apis/books.ts
  src/apis/endpoint.ts
  src/assets/_color.scss
  src/assets/_font.scss
  src/components/CommunityView/CommunityMainCard.vue
  src/components/CommunityView/CommunityReviewCard.vue
  src/components/common/Footer.vue
  src/components/common/Header.vue
  src/config/axiosLibraryConfig.ts
  src/constans/example.ts
  src/constants/book-badge.ts
  src/router/index.ts
  src/types/libraryType.ts
  src/views/AboutView.vue
  src/views/BookView.vue
  src/views/ChallengeView.vue
  src/views/CommunityView.vue
  src/views/HomeView.vue
  src/views/LibraryView.vue
  src/views/LoginView.vue
  src/views/PerformanceView.vue
  src/views/RegisterView.vue
  tsconfig.app.json
Labels: featrue

#19 fix: 로그인, 회원가입 페이지 수정 및 버튼 추가
  src/router/index.ts
  src/views/LoginView.vue
  src/views/PerformanceSearchView.vue
  src/views/RegisterView.vue
Labels: bug

#20 fix: 로그인 회원 가입 페이지 수정 및 버튼 추가 (-> main)
  src/router/index.ts
  src/views/LoginView.vue
  src/views/PerformanceSearchView.vue
  src/views/RegisterView.vue
Labels: documentation

#16 feat : 커뮤니티 메인페이지 퍼블리싱 & 페이지네이션 컴포넌트 추가
  public/icons/title-point.svg
  src/components/CommunityView/CommunityReviewCard.vue
  src/components/CommunityView/CommunityTabs.vue
  src/components/common/Pagination.vue
  src/views/CommunityView.vue
Labels: featrue
